"""Pure data tables for voice command matching: short-phrase shortcuts
for app-context commands (Photoshop/Figma), exact-phrase canon lookups,
and the fuzzy keyword/verb/pattern table. No matching logic lives here —
see commands.py for that. Split out for file-size only; commands.py
re-exports everything below so existing imports keep working.
"""

from core.nlp.commands_data_creative import _PS_SHORT, _FIGMA_SHORT

CANON_SIMPLE = {'джарвис': 'wake',
               'стоп': 'media_pause', 'пауза': 'media_pause', 'продолжай': 'media_play', 'продолжить': 'media_play', 'хватит': 'media_pause', 'останови': 'media_pause',
               'продолжай в ютубе': 'media_play_youtube', 'продолжить в ютубе': 'media_play_youtube', 
               'продолжай в youtube': 'media_play_youtube', 'продолжить в youtube': 'media_play_youtube',
               'пауза в ютубе': 'media_pause_youtube', 'стоп в ютубе': 'media_pause_youtube',
               'продолжай в браузере': 'media_play_browser', 'продолжить в браузере': 'media_play_browser',
               'пауза в браузере': 'media_pause_browser', 'стоп в браузере': 'media_pause_browser',
               'стоп мышка': 'media_pause', 'полный экран': 'yt_full', 'видео на весь экран': 'yt_full', 'плеер на весь экран': 'yt_full', 'ютуб на весь экран': 'yt_full', 'youtube на весь экран': 'yt_full', 'на весь экран': 'max_win', 'вперед': 'yt_fwd', 'вперёд': 'yt_fwd', 'дальше': 'yt_fwd', 'назад': 'yt_bwd', 'закрой': 'context_close', 'следующее видео': 'yt_next', 'следующий ролик': 'yt_next', 'предыдущее видео': 'yt_prev', 'предыдущий ролик': 'yt_prev', 'громче': 'vol_up', 'погромче': 'vol_up', 'тише': 'vol_down', 'потише': 'vol_down', 'скриншот': 'screenshot', 'правее': 'mouse_right', 'право': 'mouse_right', 'вправо': 'mouse_right', 'левее': 'mouse_left', 'лево': 'mouse_left', 'влево': 'mouse_left', 'выше': 'mouse_up', 'наверх': 'mouse_up', 'вверх': 'mouse_up', 'ниже': 'mouse_down', 'вниз': 'mouse_down', 'быстрее': 'mouse_faster', 'быстрей': 'mouse_faster', 'ускорь': 'mouse_faster', 'медленнее': 'mouse_slower', 'медленее': 'mouse_slower', 'помедленнее': 'mouse_slower', 'нажимай': 'mouse_click', 'нажми': 'mouse_click', 'клик': 'mouse_click', 'двойной клик': 'mouse_dblclick', 'молодец': 'praise', 'ты молодец': 'praise', 'умница': 'praise', 'красавчик': 'praise', 'хорошая работа': 'praise', 'отличная работа': 'praise', 'спасибо': 'thanks', 'спасибо большое': 'thanks', 'большое спасибо': 'thanks', 'благодарю': 'thanks', 'спс': 'thanks', 'перезагрузка': 'restart', 'перезагрузись': 'restart', 'скопируй': 'clip_copy', 'скопируй это': 'clip_copy', 'копируй': 'clip_copy', 'вставь': 'clip_paste', 'вставь это': 'clip_paste', 'вставить': 'clip_paste', 'ставь': 'clip_paste', 'вырежи': 'clip_cut', 'вырежи это': 'clip_cut', 'вырезать': 'clip_cut', 'отмени': 'undo', 'отмена': 'undo', 'назад действие': 'undo', 'повтори действие': 'redo', 'верни действие': 'redo', 'выдели всё': 'select_all', 'выдели все': 'select_all', 'буфер обмена': 'clip_history', 'открой буфер': 'clip_history', 'открой буфер обмена': 'clip_history', 'вставь последний элемент': 'clip_paste_last', 'вставь предпоследний элемент': 'clip_paste_prev', 'режим диктовки': 'dictation_on', 'начни диктовку': 'dictation_on', 'диктовка': 'dictation_on', 'печатай за мной': 'dictation_on', 'начинай печатать': 'dictation_on', 'очисти корзину': 'empty_trash', 'создай папку': 'create_folder', 'создай новую папку': 'create_folder', 'создать папку': 'create_folder', 'создать новую папку': 'create_folder', 'создай документ': 'create_word_doc', 'создай файл': 'create_word_doc', 'создать документ': 'create_word_doc', 'создать файл': 'create_word_doc', 'создай новый файл': 'create_word_doc', 'создать новый файл': 'create_word_doc', 'сделай новый файл': 'create_word_doc', 'создай пустой файл': 'create_word_doc', 'удали папку': 'delete_folder', 'запиши': 'note_save', 'запиши идею': 'note_save', 'сделай заметку': 'note_save', 'сохрани заметку': 'note_save', 'запомни': 'note_save', 'напомни': 'reminder', 'напомни мне': 'reminder', 'отмени напоминание': 'cancel_reminder', 'отменить напоминание': 'cancel_reminder', 'убери напоминание': 'cancel_reminder', 'отключи напоминание': 'cancel_reminder', 'распознай текст': 'ocr_screen', 'прочитай экран': 'ocr_screen', 'скопируй текст с экрана': 'ocr_screen', 'скопируй текст со скрина': 'ocr_last', 'текст со скриншота': 'ocr_last', 'прочитай скриншот': 'ocr_last', 'зайди в загрузки': 'explorer_goto', 'открой загрузки': 'explorer_goto', 'зайди в видео': 'explorer_goto', 'открой видео': 'explorer_goto', 'зайди в фото': 'explorer_goto', 'открой фото': 'explorer_goto', 'зайди в документы': 'explorer_goto', 'открой документы': 'explorer_goto', 'зайди в музыку': 'explorer_goto', 'открой музыку': 'explorer_goto', 'зайди в корзину': 'explorer_goto', 'открой корзину': 'explorer_goto', 'зайди на рабочий стол': 'explorer_goto', 'открой рабочий стол': 'explorer_goto', 'проводник': 'explorer_goto', 'открой проводник': 'explorer_goto', 'открой последний документ': 'recent_doc', 'открой последнюю таблицу': 'recent_sheet', 'открой последнюю презентацию': 'recent_pres', 'открой последний файл': 'recent_any', 'открой предпоследний документ': 'recent_doc_prev', 'открой предпоследнюю таблицу': 'recent_sheet_prev', 'открой предпоследнюю презентацию': 'recent_pres_prev', 'открой предпоследний файл': 'recent_any_prev', 'открой последнее видео': 'open_last_video', 'открой последний ролик': 'open_last_video', 'открой последнюю запись': 'open_last_video', 'покажи последнее видео': 'open_last_video', 'покажи последнюю запись': 'open_last_video', 'воспроизведи видео': 'open_last_video', 'запусти последнее видео': 'open_last_video', 'открой последнее видео в клипчамп': 'open_last_video', 'открой видео в клипчамп': 'open_last_video', 'открой последнее видео в плеере': 'open_last_video', 'открой последнее видео в медиаплеере': 'open_last_video', 'открой последнее видео в ютубе': 'yt_last_watched', 'покажи последнее видео в ютубе': 'yt_last_watched', 'открой последний ролик в ютубе': 'yt_last_watched', 'покажи последний ролик в ютубе': 'yt_last_watched', 'что я смотрел в ютубе': 'yt_last_watched', 'последнее просмотренное видео': 'yt_last_watched', 'открой историю ютуба': 'yt_last_watched', 'открой диспетчер задач': 'open_task_manager', 'запусти диспетчер задач': 'open_task_manager', 'покажи диспетчер задач': 'open_task_manager', 'диспетчер задач': 'open_task_manager', 'открой таск менеджер': 'open_task_manager', 'открой обс': 'open_obs', 'запусти обс': 'open_obs', 'открой obs': 'open_obs', 'запусти obs': 'open_obs', 
'открой браузер': 'open_browser', 'запусти браузер': 'open_browser',
'закрой браузер': 'close_browser',
'открой дискорд': 'open_discord', 'запусти дискорд': 'open_discord', 'открой discord': 'open_discord', 'запусти discord': 'open_discord',
'закрой дискорд': 'close_discord', 'закрой discord': 'close_discord',
'открой телеграм': 'open_telegram', 'запусти телеграм': 'open_telegram', 'открой телегу': 'open_telegram',
'закрой телеграм': 'close_telegram', 'закрой telegram': 'close_telegram', 'закрой телегу': 'close_telegram',
'открой фотошоп': 'open_photoshop', 'запусти фотошоп': 'open_photoshop',
'закрой фотошоп': 'close_photoshop', 'закрой photoshop': 'close_photoshop',
'открой стим': 'open_steam', 'запусти стим': 'open_steam',
'закрой стим': 'close_steam', 'закрой steam': 'close_steam',
'открой код': 'open_vscode', 'запусти код': 'open_vscode', 'открой vscode': 'open_vscode',
'закрой код': 'close_vscode', 'закрой vscode': 'close_vscode',
'открой вайбер': 'open_viber', 'запусти вайбер': 'open_viber',
'закрой вайбер': 'close_viber', 'закрой viber': 'close_viber',
'открой вотсап': 'open_whatsapp', 'запусти вотсап': 'open_whatsapp',
'закрой вотсап': 'close_whatsapp', 'закрой whatsapp': 'close_whatsapp',
'открой эксель': 'open_excel', 'запусти эксель': 'open_excel',
'закрой эксель': 'close_excel', 'закрой excel': 'close_excel',
'открой ворд': 'open_word', 'запусти ворд': 'open_word',
'закрой ворд': 'close_word', 'закрой word': 'close_word',
'открой курсор': 'open_antigravity', 'запусти курсор': 'open_antigravity',
'закрой курсор': 'close_antigravity', 'закрой cursor': 'close_antigravity',
'найди документ': 'find_doc', 'найди таблицу': 'find_sheet', 'найди файл': 'find_file', 'покажи хад': 'show_hud', 'открой хад': 'show_hud', 'покажи интерфейс': 'show_hud',
'открой интерфейс': 'show_hud', 'открой джарвиса': 'show_hud', 'покажи джарвиса': 'show_hud',
'верни хад': 'show_hud', 'хад покажи': 'show_hud',
'помощь': 'show_help', 'покажи помощь': 'show_help', 'открой помощь': 'show_help',
'что ты умеешь': 'show_help', 'что ты можешь': 'show_help',
'расскажи о себе': 'show_help', 'расскажи что умеешь': 'show_help',
'покажи руководство': 'show_help', 'открой руководство': 'show_help',
'покажи возможности': 'show_help', 'что ты знаешь': 'show_help',
    'сверни все окна': 'min_all',
    'свернуть все окна': 'min_all',
    'сверни всё': 'min_all',
    'сверни окно': 'min_win',
    'свернуть окно': 'min_win',
    'сверни это окно': 'min_win',
    'минимизируй окно': 'min_win',
    'минимизировать окно': 'min_win',
    'удали файл': 'delete_file',
    'удали документ': 'delete_file',
    'сотри файл': 'delete_file',
'перезапусти джарвиса': 'restart_jarvis', 'перезапустить джарвиса': 'restart_jarvis',
'перезагрузи джарвиса': 'restart_jarvis', 'перезапусти джарвис': 'restart_jarvis',
'перезапустить джарвис': 'restart_jarvis', 'перезагрузить джарвиса': 'restart_jarvis',
'го в ets': 'game_mode_on', 'го в etс': 'game_mode_on', 'го в ets2': 'game_mode_on',
'го в етс': 'game_mode_on', 'го в ets 2': 'game_mode_on',
'го в евро трак': 'game_mode_on', 'го в евротрак': 'game_mode_on',
'го в трак': 'game_mode_on', 'го в трак симулятор': 'game_mode_on',
'запусти евро трак': 'game_mode_on', 'запусти ets': 'game_mode_on',
'запусти ets2': 'game_mode_on', 'включи евро трак': 'game_mode_on',
'играть в ets': 'game_mode_on', 'играть в евро трак': 'game_mode_on',
'хочу в ets': 'game_mode_on', 'хочу в евро трак': 'game_mode_on',
'го в фс': 'game_mode_on', 'го в фс22': 'game_mode_on', 'го в фс25': 'game_mode_on',
'го в фарминг': 'game_mode_on', 'го в ферму': 'game_mode_on',
'го в farming': 'game_mode_on', 'го в fs22': 'game_mode_on', 'го в fs25': 'game_mode_on',
'запусти фарминг': 'game_mode_on', 'запусти фс': 'game_mode_on',
'включи фарминг': 'game_mode_on', 'играть в фарминг': 'game_mode_on',
'хочу в фарминг': 'game_mode_on', 'хочу в ферму': 'game_mode_on',
'го в хогвартс': 'game_mode_on', 'го в хог': 'game_mode_on',
'запусти хогвартс': 'game_mode_on', 'включи хогвартс': 'game_mode_on',
'играть в хогвартс': 'game_mode_on',
 'охраняй': 'guard_on', 'режим охраны': 'guard_on', 'включи охрану': 'guard_on', 'вольно': 'guard_off', 'отбой охраны': 'guard_off', 'выключи охрану': 'guard_off', 'игровой режим': 'game_mode_on', 'режим игры': 'game_mode_on', 'активируй игровой режим': 'game_mode_on', 'подготовь к игре': 'game_mode_on', 'выйди из игрового режима': 'game_mode_off', 'отключи игровой режим': 'game_mode_off', 'отмени игровой режим': 'game_mode_off', 'отмени режим': 'game_mode_off', 'выключи игровой режим': 'game_mode_off', 'выйди из игры': 'game_mode_off', 'отмени режим игры': 'game_mode_off', 'конец игры': 'game_mode_off', 'игра окончена': 'game_mode_off', 'верни обычный режим': 'game_mode_off', 'который час': 'time_now', 'сколько время': 'time_now', 'скажи время': 'time_now', 'время': 'time_now', 'текущее время': 'time_now', 'сколько сейчас времени': 'time_now', 'статус системы': 'system_status', 'состояние системы': 'system_status', 'как система': 'system_status', 'отчет о системе': 'system_status', 'системный статус': 'system_status', 'переключи звук на': 'audio_switch', 'звук на колонки': 'audio_switch', 'звук на наушники': 'audio_switch', 'включи режим экономии': 'economy_on', 'активируй режим экономии': 'economy_on', 'отключи режим экономии': 'economy_off', 'отмени режим экономии': 'economy_off', 'сделай уборку': 'system_cleanup', 'приберись': 'system_cleanup', 'уборка': 'system_cleanup', 'сделай глубокую уборку': 'system_cleanup_deep', 'глубокая уборка': 'system_cleanup_deep', 'найди мусор от программ': 'system_cleanup_deep', 'проверь компьютер на мусор от старых программ': 'system_cleanup_deep', 'проверь интернет': 'internet_speed', 'скорость интернета': 'internet_speed', 'какая скорость интернета': 'internet_speed', 'тест интернета': 'internet_speed', 'убавь яркость': 'brightness_down', 'уменьши яркость': 'brightness_down', 'сделай потемнее': 'brightness_down', 'яркость на': 'brightness_set', 'сделай яркость на': 'brightness_set', 'установи яркость на': 'brightness_set', 'не слушай меня': 'listen_off', 'не слушай': 'listen_off', 'перестань слушать': 'listen_off',
'режим тишины': 'listen_off', 'включи режим тишины': 'listen_off', 'активируй режим тишины': 'listen_off',
'уйди в спячку': 'listen_off', 'иди в спячку': 'listen_off', 'иди спать': 'listen_off',
'джарвис молчи': 'listen_off', 'джарвис стой': 'listen_off', 'подожди меня': 'listen_off',
'не подслушивай': 'listen_off', 'не мешай': 'listen_off', 'не слушай нас': 'listen_off',
'я говорю не с тобой': 'listen_off', 'это не тебе': 'listen_off',
'стоп слушать': 'listen_off', 'выключи прослушивание': 'listen_off',
'жди': 'listen_off', 'подожди': 'listen_off', 'подождите': 'listen_off',
 'слушай меня': 'listen_on', 'начни слушать': 'listen_on', 'как ты': 'how_are_you', 'как дела': 'how_are_you', 'как самочувствие': 'how_are_you', 'слушай': 'listen_on', 'скачай': 'download_video', 'скачать': 'download_video', 'загрузи': 'download_video', 'сохрани': 'save_video', 'сохрани видео': 'save_video', 'запомни видео': 'save_video', 'джарвис скачай': 'download_video', 'джарвис скачай это видео': 'download_video', 'джарвис открой последнее видео на ютубе': 'yt_last_watched', 'открой последнее видео на ютубе': 'yt_last_watched', 'покажи последнее видео на ютубе': 'yt_last_watched', 'что я смотрел на ютубе': 'yt_last_watched', 'открой ютуб историю': 'yt_last_watched', 'покажи ютуб историю': 'yt_last_watched', 'открой сохраненное видео': 'open_saved', 'открой сохранённое видео': 'open_saved',
'открой первое сохранённое видео': 'open_saved', 'открой первое сохраненное видео': 'open_saved',
'открой второе сохранённое видео': 'open_saved', 'открой второе сохраненное видео': 'open_saved',
'открой третье сохранённое видео': 'open_saved', 'открой третье сохраненное видео': 'open_saved',
'открой четвёртое сохранённое видео': 'open_saved', 'открой четвертое сохраненное видео': 'open_saved',
'открой пятое сохранённое видео': 'open_saved', 'открой пятое сохраненное видео': 'open_saved',
'открой шестое сохранённое видео': 'open_saved', 'открой шестое сохраненное видео': 'open_saved',
'открой седьмое сохранённое видео': 'open_saved', 'открой седьмое сохраненное видео': 'open_saved',
'открой восьмое сохранённое видео': 'open_saved', 'открой восьмое сохраненное видео': 'open_saved',
'открой девятое сохранённое видео': 'open_saved', 'открой девятое сохраненное видео': 'open_saved',
'открой десятое сохранённое видео': 'open_saved', 'открой десятое сохраненное видео': 'open_saved',
'открой последнее сохранённое видео': 'open_saved', 'открой последнее сохраненное видео': 'open_saved',
'открой 1 сохранённое видео': 'open_saved', 'открой 1 сохраненное видео': 'open_saved',
'открой 2 сохранённое видео': 'open_saved', 'открой 2 сохраненное видео': 'open_saved',
'открой 3 сохранённое видео': 'open_saved', 'открой 3 сохраненное видео': 'open_saved',
'открой 4 сохранённое видео': 'open_saved', 'открой 4 сохраненное видео': 'open_saved',
'открой 5 сохранённое видео': 'open_saved', 'открой 5 сохраненное видео': 'open_saved',
'открой 6 сохранённое видео': 'open_saved', 'открой 6 сохраненное видео': 'open_saved',
'открой 7 сохранённое видео': 'open_saved', 'открой 7 сохраненное видео': 'open_saved',
'открой 8 сохранённое видео': 'open_saved', 'открой 8 сохраненное видео': 'open_saved',
'открой 9 сохранённое видео': 'open_saved', 'открой 9 сохраненное видео': 'open_saved',
    'открой ютуб': 'open_youtube', 'запусти ютуб': 'open_youtube', 'включи ютуб': 'open_youtube', 'открой youtube': 'open_youtube', 'запусти youtube': 'open_youtube', 'открой ютубчик': 'open_youtube',
    'джарвис открой ютуб': 'open_youtube', 'джарвис запусти ютуб': 'open_youtube', 'джарвис открой youtube': 'open_youtube',
    'покажи хад': 'show_hud', 'открой хад': 'show_hud', 'покажи худ': 'show_hud', 'открой худ': 'show_hud', 'открйо худ': 'show_hud', 'покажи интерфейс': 'show_hud', 'открой интерфейс': 'show_hud', 'разверни худ': 'show_hud', 'разверни хад': 'show_hud',
    'скрой худ': 'min_win', 'сверни худ': 'min_win', 'убери худ': 'min_win', 'закрой худ': 'min_win',
'открой настройки': 'open_settings', 'покажи настройки': 'open_settings', 'настройки системы': 'open_settings',
'установи город': 'set_weather_city', 'запомни город': 'set_weather_city', 'смени город': 'set_weather_city', 'мой город': 'set_weather_city',
'открой макросы': 'open_keybinds', 'открой клавиши': 'open_keybinds', 'настрой клавиши': 'open_keybinds', 'бинды': 'open_keybinds', 'настройка кнопок': 'open_keybinds',
    'открой расширения': 'open_extensions', 'покажи расширения': 'open_extensions', 'центр модулей': 'open_extensions',
    'мониторинг ресурсов': 'open_perf', 'открой мониторинг': 'open_perf', 'покажи нагрузку': 'open_perf', 'статус ресурсов': 'open_perf',
    'какие команды ты знаешь': 'open_deck', 'покажи все команды': 'open_deck', 'открой базу команд': 'open_deck', 'база команд': 'open_deck', 'список команд': 'open_deck', 'все команды': 'open_deck', 'покажи команды': 'open_deck',
    'перезапусти джарвиса': 'restart_jarvis', 'перезагрузи джарвиса': 'restart_jarvis', 'перезапусти джарвис': 'restart_jarvis',
    'курс доллара': 'currency_rate', 'курс евро': 'currency_rate', 'курс биткоина': 'currency_rate',
    'какой курс': 'currency_rate', 'курс валюты': 'currency_rate', 'курс фунта': 'currency_rate',
    # Распознавание песни
    'что за песня': 'song_id', 'что это за песня': 'song_id', 'какая это песня': 'song_id',
    'угадай песню': 'song_id', 'узнай песню': 'song_id', 'распознай песню': 'song_id', 'что играет': 'song_id',
    # Звук
    'максимальная громкость': 'vol_max', 'сделай максимально': 'vol_max',
    'включи звук': 'vol_unmute', 'убери тишину': 'vol_unmute',
    'тишина': 'vol_mute', 'нулевая громкость': 'vol_zero',
    'громкость на ноль': 'vol_zero',
    # Яркость
    'прибавь яркость': 'brightness_up', 'сделай поярче': 'brightness_up',
    # Сеть
    'мой ip': 'my_ip', 'какой мой ip': 'my_ip', 'покажи ip': 'my_ip',
    # Система
    'за работу': 'work_session', 'начнём работу': 'work_session', 'открой проект': 'work_session',
    'завершить работу джарвиса': 'jarvis_exit', 'закрой джарвиса': 'jarvis_exit',
    # Exact phrases so these never fall through to fuzzy matching against
    # 'work_session's CANON keys — "работу" being an exact-word match there
    # was outscoring the longer, correct 'завершить работу джарвиса' key,
    # so a plain "заверши работу" was misfiring as "start a work session"
    # instead of quitting.
    'заверши работу': 'jarvis_exit', 'закончи работу': 'jarvis_exit',
    'закончил работу': 'jarvis_exit', 'завершил работу': 'jarvis_exit',
    'закончить работу': 'jarvis_exit', 'завершить работу': 'jarvis_exit',
    'отключись': 'jarvis_exit', 'выключись': 'jarvis_exit',
    'выйди из папки': 'explorer_go_up', 'выйди из запущенной игры': 'exit_game',
    'разверни последнее окно': 'unmin_win', 'открой последнее окно': 'unmin_win',
    'закрой все окна': 'close_all_win', 'закрыть все окна': 'close_all_win',
    'закрой остальные окна': 'close_other_win',
    'закрой окно': 'close_win', 'закрыть окно': 'close_win',
    'закрой вкладку': 'close_tab', 'закрыть вкладку': 'close_tab',
    'закрой все вкладки': 'close_all_tabs', 'закрыть все вкладки': 'close_all_tabs',
    'сверни остальные': 'min_other_win',
    'перенеси на другой монитор': 'move_monitor', 'на второй монитор': 'move_monitor',
    'заблокируй клавиатуру': 'keyboard_lock', 'клавиатура выкл': 'keyboard_lock',
    'разблокируй клавиатуру': 'keyboard_unlock', 'клавиатура вкл': 'keyboard_unlock',
    'нажми энтер': 'press_enter', 'нажми enter': 'press_enter', 'подтверди': 'press_enter',
    # Терминал
    'открой терминал': 'open_terminal', 'запусти терминал': 'open_terminal',
    'скриншот сайта': 'screenshot_site',
    'скриншот страницы': 'screenshot_site', 'скрин страницы': 'screenshot_site',
    'сделай скриншот страницы': 'screenshot_site', 'скриншот всей страницы': 'screenshot_site',
    'скриншот терминала': 'screenshot_terminal', 'скрин терминала': 'screenshot_terminal',
    'сделай скриншот терминала': 'screenshot_terminal',
    'прочитай последний скриншот': 'ocr_last', 'распознай последний скриншот': 'ocr_last',
    # Почта
    'напиши письмо': 'mail_compose', 'создай письмо': 'mail_compose', 'новое письмо': 'mail_compose',
    'сколько писем': 'inbox_unread', 'непрочитанные письма': 'inbox_unread',
    # Медиа
    'начни запись': 'start_video', 'запись экрана': 'start_video', 'начать запись': 'start_video',
    'стоп запись': 'stop_video', 'остановить запись': 'stop_video',
    'открой историю браузера': 'open_browser_history', 'история браузера': 'open_browser_history', 'открой историю': 'open_browser_history', 'история': 'open_browser_history',
    'переводи': 'translate', 'переведи': 'translate', 'переведи текст': 'translate',
    'переводи голос': 'translate_speech', 'переводи речь': 'translate_speech',
    # Bluetooth
    'подключи bluetooth': 'bt_connect', 'подключи блютуз устройство': 'bt_connect',
    'отключи bluetooth устройство': 'bt_disconnect',
    'покажи bluetooth': 'bt_list', 'список bluetooth': 'bt_list',
    # Календарь
    'следующее событие': 'calendar_next', 'что в календаре': 'calendar_next', 'мое расписание': 'calendar_next',
    # Сводка
    'сводка на сегодня': 'today_summary', 'что сегодня': 'today_summary',
    # Диски
    'здоровье дисков': 'health_disks', 'проверь диски': 'health_disks', 'состояние дисков': 'health_disks',
}
_INSULT = 'system_insult'


CANON_SIMPLE.update({'правее': 'mouse_right', 'левее': 'mouse_left', 'выше': 'mouse_up', 'ниже': 'mouse_down', 'быстрее': 'mouse_faster', 'медленнее': 'mouse_slower', 'ускорь': 'mouse_faster', 'замедли': 'mouse_slower', 'стоп': 'media_pause', 'хватит': 'media_pause', 'остановись': 'media_pause', 'замри': 'media_pause',
    'ты дурак': _INSULT, 'ты дура': _INSULT, 'дурак': _INSULT,
    'автолейаут': 'figma_auto_layout', 'сгруппируй': 'figma_group', 'кисть': 'ps_brush', 'ластик': 'ps_eraser'
})

CANON_SIMPLE_UK = {
    # --- Wake ---
    'джарвіс': 'wake',
    'відкрий браузер': 'open_browser', 'запусти браузер': 'open_browser',
    'закрий браузер': 'close_browser', 'зачини браузер': 'close_browser', 'закрити браузер': 'close_browser',
    'відкрий дискорд': 'open_discord', 'запусти дискорд': 'open_discord', 'відкрий discord': 'open_discord',
    'закрий дискорд': 'close_discord', 'зачини дискорд': 'close_discord', 'закрити дискорд': 'close_discord', 'закрий discord': 'close_discord', 'зачини discord': 'close_discord',
    'відкрий телеграм': 'open_telegram', 'запусти телеграм': 'open_telegram', 'відкрий телегу': 'open_telegram',
    'закрий телеграм': 'close_telegram', 'зачини телеграм': 'close_telegram', 'закрити телеграм': 'close_telegram', 'закрий telegram': 'close_telegram', 'зачини telegram': 'close_telegram', 'закрий телегу': 'close_telegram',
    'відкрий youtube': 'open_youtube', 'запусти youtube': 'open_youtube', 'відкрий ютуб': 'open_youtube', 'запусти ютуб': 'open_youtube',
    'відкрий фотошоп': 'open_photoshop', 'запусти фотошоп': 'open_photoshop',
    'закрий фотошоп': 'close_photoshop', 'зачини фотошоп': 'close_photoshop', 'закрити фотошоп': 'close_photoshop', 'закрий photoshop': 'close_photoshop',
    'відкрий стім': 'open_steam', 'запусти стім': 'open_steam', 'відкрий steam': 'open_steam',
    'закрий стім': 'close_steam', 'зачини стім': 'close_steam', 'закрити стім': 'close_steam', 'закрий steam': 'close_steam', 'зачини steam': 'close_steam', 'закрити steam': 'close_steam',
    'відкрий код': 'open_vscode', 'запусти код': 'open_vscode', 'відкрий vscode': 'open_vscode',
    'закрий код': 'close_vscode', 'зачини код': 'close_vscode', 'закрити код': 'close_vscode', 'закрий vscode': 'close_vscode',
    'відкрий вайбер': 'open_viber', 'запусти вайбер': 'open_viber',
    'закрий вайбер': 'close_viber', 'зачини вайбер': 'close_viber', 'закрити вайбер': 'close_viber', 'закрий viber': 'close_viber',
    'відкрий вотсап': 'open_whatsapp', 'запусти вотсап': 'open_whatsapp',
    'закрий вотсап': 'close_whatsapp', 'зачини вотсап': 'close_whatsapp', 'закрити вотсап': 'close_whatsapp', 'закрий whatsapp': 'close_whatsapp',
    'відкрий ексель': 'open_excel', 'запусти ексель': 'open_excel',
    'закрий ексель': 'close_excel', 'зачини ексель': 'close_excel', 'закрити ексель': 'close_excel', 'закрий excel': 'close_excel',
    'відкрий ворд': 'open_word', 'запусти ворд': 'open_word',
    'закрий ворд': 'close_word', 'зачини ворд': 'close_word', 'закрити ворд': 'close_word', 'закрий word': 'close_word',
    'відкрий обс': 'open_obs', 'запусти обс': 'open_obs', 'відкрий obs': 'open_obs',
    'закрий обс': 'close_obs', 'зачини обс': 'close_obs', 'закрити обс': 'close_obs', 'закрий obs': 'close_obs',
    'відкрий курсор': 'open_antigravity', 'запусти курсор': 'open_antigravity',
    'закрий курсор': 'close_antigravity', 'зачини курсор': 'close_antigravity', 'закрити курсор': 'close_antigravity',
    'диспетчер завдань': 'open_task_manager', 'відкрий диспетчер завдань': 'open_task_manager',
    # --- Гучність / яскравість ---
    'гучніше': 'vol_up', 'погучніше': 'vol_up',
    'тихіше': 'vol_down', 'потихіше': 'vol_down',
    'гучність на': 'vol_set', 'звук на': 'vol_set', 'постав гучність': 'vol_set',
    'вимкни звук': 'vol_mute', 'замовчи': 'vol_mute',
    'зменши яскравість': 'brightness_down', 'темніше': 'brightness_down',
    'яскравість на': 'brightness_set',
    'звук на колонки': 'audio_switch', 'звук на навушники': 'audio_switch', 'переключи звук': 'audio_switch',
    # --- Медіа ---
    'пауза': 'media_pause', 'зупини': 'media_pause', 'стій': 'media_pause', 'зупинити': 'media_pause',
    'продовжуй': 'media_play', 'продовжити': 'media_play', 'відтворити': 'media_play',
    'пауза в ютубі': 'media_pause_youtube', 'зупини ютуб': 'media_pause_youtube',
    'продовжуй в ютубі': 'media_play_youtube', 'продовжити в ютубі': 'media_play_youtube',
    'пауза в браузері': 'media_pause_browser', 'зупини в браузері': 'media_pause_browser',
    'продовжуй в браузері': 'media_play_browser',
    'вперед': 'yt_fwd', 'далі': 'yt_fwd',
    'назад': 'yt_bwd',
    'повний екран': 'yt_full', 'відео на весь екран': 'yt_full', 'на весь екран': 'yt_full',
    'наступне відео': 'yt_next', 'наступний ролик': 'yt_next',
    'попереднє відео': 'yt_prev', 'попередній ролик': 'yt_prev',
    'відкрий останнє відео': 'open_last_video', 'покажи останнє відео': 'open_last_video',
    'відкрий останнє відео на ютубі': 'yt_last_watched', 'що я дивився на ютубі': 'yt_last_watched',
    # --- Скріншот / OCR ---
    'скріншот': 'screenshot',
    'розпізнай текст': 'ocr_screen', 'прочитай екран': 'ocr_screen', 'скопіюй текст з екрана': 'ocr_screen',
    'текст зі скріншота': 'ocr_last', 'прочитай скріншот': 'ocr_last',
    # --- Буфер обміну ---
    'скопіюй': 'clip_copy', 'копіювати': 'clip_copy',
    'встав': 'clip_paste', 'вставити': 'clip_paste',
    'виріж': 'clip_cut', 'вирізати': 'clip_cut',
    'буфер обміну': 'clip_history', 'відкрий буфер': 'clip_history',
    'встав останній елемент': 'clip_paste_last',
    'встав передостанній елемент': 'clip_paste_prev',
    # --- Вікна ---
    'заверни всі вікна': 'min_all', 'згорни все': 'min_all', 'згорни всі вікна': 'min_all',
    'на весь екран вікно': 'max_win', 'розгорни вікно': 'max_win',
    'закрий': 'context_close', 'закрити': 'context_close',
    'згорни': 'min_win', 'схований': 'min_win', 'сховай хад': 'min_win',
    'покажи хад': 'show_hud', 'відкрий хад': 'show_hud', 'покажи інтерфейс': 'show_hud',
    # --- Мишка ---
    'мишка вправо': 'mouse_right', 'правіше': 'mouse_right',
    'мишка вліво': 'mouse_left', 'лівіше': 'mouse_left',
    'мишка вверх': 'mouse_up', 'вище': 'mouse_up',
    'мишка вниз': 'mouse_down', 'нижче': 'mouse_down',
    'швидше': 'mouse_faster', 'прискорити': 'mouse_faster',
    'повільніше': 'mouse_slower', 'сповільнити': 'mouse_slower',
    'натисни': 'mouse_click', 'клік': 'mouse_click', 'натиснути': 'mouse_click',
    'подвійний клік': 'mouse_dblclick',
    # --- Час / система ---
    'котра година': 'time_now', 'скільки часу': 'time_now', 'скільки зараз часу': 'time_now',
    'статус системи': 'system_status', 'стан системи': 'system_status', 'як система': 'system_status',
    'зроби прибирання': 'system_cleanup', 'очисти комп': 'system_cleanup', 'прибирання': 'system_cleanup',
    'зроби глибоке прибирання': 'system_cleanup_deep', 'глибоке прибирання': 'system_cleanup_deep', 'знайди сміття від програм': 'system_cleanup_deep',
    'перевір інтернет': 'internet_speed', 'швидкість інтернету': 'internet_speed',
    'перезавантаж': 'restart', 'перезапуск': 'restart',
    'перезапусти джарвіса': 'restart_jarvis', 'перезавантаж джарвіса': 'restart_jarvis',
    # --- Файли ---
    'створи папку': 'create_folder', 'нова папка': 'create_folder',
    'створи документ': 'create_word_doc', 'створи файл': 'create_word_doc', 'створи новий файл': 'create_word_doc', 'зроби новий файл': 'create_word_doc',
    'видали файл': 'delete_file', 'видалити файл': 'delete_file',
    'видали папку': 'delete_folder',
    'очисти кошик': 'empty_trash', 'кошик': 'empty_trash',
    'відкрий провідник': 'explorer_goto', 'провідник': 'explorer_goto',
    'відкрий завантаження': 'explorer_goto', 'відкрий документи': 'explorer_goto',
    'знайди документ': 'find_doc', 'знайди таблицю': 'find_sheet', 'знайди файл': 'find_file',
    'відкрий останній документ': 'recent_doc', 'відкрий останній файл': 'recent_any',
    'відкрий останню таблицю': 'recent_sheet', 'відкрий останню презентацію': 'recent_pres',
    'відкрий передостанній документ': 'recent_doc_prev', 'відкрий передостанній файл': 'recent_any_prev',
    'відкрий передостанню таблицю': 'recent_sheet_prev', 'відкрий передостанню презентацію': 'recent_pres_prev',
    # --- Нотатки / нагадування ---
    'запиши': 'note_save', 'зроби нотатку': 'note_save', 'запам\'ятай': 'note_save',
    'відміни нагадування': 'cancel_reminder', 'скасуй нагадування': 'cancel_reminder',
    # --- Режими ---
    'ігровий режим': 'game_mode_on', 'активуй ігровий режим': 'game_mode_on',
    'вимкни ігровий режим': 'game_mode_off', 'вийди з ігрового режиму': 'game_mode_off',
    'режим охорони': 'guard_on', 'увімкни охорону': 'guard_on',
    'вимкни охорону': 'guard_off', 'відбій охорони': 'guard_off',
    'режим економії': 'economy_on', 'увімкни режим економії': 'economy_on',
    'вимкни режим економії': 'economy_off',
    'режим диктування': 'dictation_on', 'почни диктування': 'dictation_on', 'диктування': 'dictation_on',
    'не слухай': 'listen_off', 'замовкни': 'listen_off', 'зупини прослуховування': 'listen_off',
    'слухай мене': 'listen_on', 'почни слухати': 'listen_on',
    # --- Відповіді ---
    'як ти': 'how_are_you', 'як справи': 'how_are_you', 'які дела': 'how_are_you',
    'молодець': 'praise', 'ти молодець': 'praise', 'гарна робота': 'praise',
    'дякую': 'thanks', 'дуже дякую': 'thanks', 'дякую тобі': 'thanks', 'спасибі': 'thanks',
    # --- Налаштування / розширення ---
    'відкрий налаштування': 'open_settings', 'налаштування': 'open_settings',
    'відкрий розширення': 'open_extensions', 'центр модулів': 'open_extensions',
    'відкрий макроси': 'open_keybinds', 'налаштуй клавіші': 'open_keybinds',
    'які команди ти знаєш': 'open_deck', 'покажи всі команди': 'open_deck', 'відкрий базу команд': 'open_deck', 'база команд': 'open_deck', 'список команд': 'open_deck', 'всі команди': 'open_deck', 'покажи команди': 'open_deck',
    'моніторинг ресурсів': 'open_perf', 'відкрий моніторинг': 'open_perf',
    'допоможи': 'show_help', 'що ти вмієш': 'show_help', 'що ти можеш': 'show_help',
    # --- Дії з текстом ---
    'відміни': 'undo', 'відмінити': 'undo',
    'повтори дію': 'redo', 'поверни дію': 'redo',
    'виділи все': 'select_all', 'виділити все': 'select_all',
    # --- Відео ---
    'скачай': 'download_video', 'завантаж': 'download_video', 'скачати': 'download_video',
    'збережи відео': 'save_video', 'запам\'ятай відео': 'save_video',
    'відкрий збережене відео': 'open_saved',
    # --- Міста / погода ---
    'встанови місто': 'set_weather_city', 'змінити місто': 'set_weather_city', 'моє місто': 'set_weather_city',
    # --- Лайка ---
    'ти дурень': 'system_insult', 'дурень': 'system_insult', 'ти дура': 'system_insult',
    'йди нахер': 'system_insult', 'йди лісом': 'system_insult', 'заткнись': 'system_insult',
    # --- Фотошоп / Фігма ---
    'пензель': 'ps_brush', 'візьми пензель': 'ps_brush',
    'гумка': 'ps_eraser', 'візьми гумку': 'ps_eraser',
    'збережи проект': 'ps_save', 'зберегти в фотошопі': 'ps_save',
    'автолейаут': 'figma_auto_layout',
    'згрупуй': 'figma_group', 'зроби групу': 'figma_group',
    # --- Система / ПК ---
    'вимкни комп': 'shutdown', 'вимкни комп\'ютер': 'shutdown', 'вимкни пк': 'shutdown',
    'характеристики': 'system_specs', 'характеристики комп\'ютера': 'system_specs', 'яке залізо': 'system_specs',
    'закрий вікно': 'close_win', 'закрити вікно': 'close_win',
    'вікно вліво': 'win_snap_left', 'притисни вліво': 'win_snap_left',
    'вікно вправо': 'win_snap_right', 'притисни вправо': 'win_snap_right',
    'вийди з папки': 'explorer_go_up', 'рівень вище': 'explorer_go_up',
    'встав файл': 'paste_file', 'вставити файл': 'paste_file',
    'зроби коміт': 'git_commit', 'відправ зміни': 'git_commit',
    'вимкни вайфай': 'wifi_toggle', 'увімкни вайфай': 'wifi_toggle', 'вимкни wifi': 'wifi_toggle',
    'вимкни блютуз': 'bluetooth_toggle', 'увімкни блютуз': 'bluetooth_toggle',
    'скасуй виключення': 'cancel_timer', 'не вимикай': 'cancel_timer',
    # --- Валюта ---
    'курс долара': 'currency_rate', 'курс євро': 'currency_rate', 'курс біткоїна': 'currency_rate',
    'який курс': 'currency_rate', 'курс валюти': 'currency_rate', 'курс фунта': 'currency_rate',
    # --- Розпізнавання пісні ---
    'що за пісня': 'song_id', 'що це за пісня': 'song_id', 'яка це пісня': 'song_id',
    'вгадай пісню': 'song_id', 'впізнай пісню': 'song_id', 'розпізнай пісню': 'song_id', 'що грає': 'song_id',
    # --- Звук ---
    'максимальна гучність': 'vol_max', 'зроби максимально': 'vol_max',
    'увімкни звук': 'vol_unmute', 'прибери тишу': 'vol_unmute',
    'тиша': 'vol_mute', 'нульова гучність': 'vol_zero', 'гучність на нуль': 'vol_zero',
    # --- Яскравість ---
    'збільши яскравість': 'brightness_up', 'зроби яскравіше': 'brightness_up',
    # --- Мережа ---
    'мій ip': 'my_ip', 'який мій ip': 'my_ip', 'покажи ip': 'my_ip',
    # --- Система ---
    'до роботи': 'work_session', 'відкрий проект': 'work_session',
    'закрий джарвіса': 'jarvis_exit', 'завершити джарвіса': 'jarvis_exit',
    'заверши роботу': 'jarvis_exit', 'закінчи роботу': 'jarvis_exit',
    'закінчив роботу': 'jarvis_exit', 'завершив роботу': 'jarvis_exit',
    'закінчити роботу': 'jarvis_exit', 'завершити роботу': 'jarvis_exit',
    'відключись': 'jarvis_exit', 'вимкнись': 'jarvis_exit',
    'вийди із запущеної гри': 'exit_game',
    'розгорни останнє вікно': 'unmin_win', 'відкрий останнє вікно': 'unmin_win',
    'закрий всі вікна': 'close_all_win', 'закрити всі вікна': 'close_all_win',
    'закрий інші вікна': 'close_other_win',
    'згорни інші': 'min_other_win',
    'перенеси на інший монітор': 'move_monitor', 'на другий монітор': 'move_monitor',
    'заблокуй клавіатуру': 'keyboard_lock', 'клавіатура вимк': 'keyboard_lock',
    'розблокуй клавіатуру': 'keyboard_unlock', 'клавіатура увімк': 'keyboard_unlock',
    'натисни ентер': 'press_enter', 'натисни enter': 'press_enter', 'підтверди': 'press_enter',
    # --- Термінал ---
    'відкрий термінал': 'open_terminal', 'запусти термінал': 'open_terminal',
    'скріншот сайту': 'screenshot_site',
    'скріншот сторінки': 'screenshot_site', 'скрін сторінки': 'screenshot_site',
    'зроби скріншот сторінки': 'screenshot_site', 'скріншот усієї сторінки': 'screenshot_site',
    'скріншот терміналу': 'screenshot_terminal', 'скрін терміналу': 'screenshot_terminal',
    'зроби скріншот терміналу': 'screenshot_terminal',
    'прочитай останній скріншот': 'ocr_last', 'розпізнай останній скріншот': 'ocr_last',
    # --- Пошта ---
    'напиши листа': 'mail_compose', 'створи листа': 'mail_compose', 'новий лист': 'mail_compose',
    'скільки листів': 'inbox_unread', 'непрочитані листи': 'inbox_unread',
    # --- Медіа ---
    'почни запис': 'start_video', 'запис екрану': 'start_video', 'почати запис': 'start_video',
    'стоп запис': 'stop_video', 'зупинити запис': 'stop_video',
    'відкрий історію браузера': 'open_browser_history', 'історія браузера': 'open_browser_history', 'відкрий історію': 'open_browser_history', 'історія': 'open_browser_history',
    'перекладай': 'translate', 'переклади': 'translate', 'переклади текст': 'translate',
    'перекладай голос': 'translate_speech', 'переклади мову': 'translate_speech',
    # --- Bluetooth ---
    'підключи bluetooth': 'bt_connect', 'підключити bluetooth': 'bt_connect',
    'відключи bluetooth': 'bt_disconnect',
    'покажи bluetooth': 'bt_list', 'список bluetooth': 'bt_list',
    # --- Календар ---
    'наступна подія': 'calendar_next', 'що в календарі': 'calendar_next', 'мій розклад': 'calendar_next',
    # --- Зведення ---
    'зведення на сьогодні': 'today_summary', 'що сьогодні': 'today_summary',
    # --- Диски ---
    'здоров\'я дисків': 'health_disks', 'перевір диски': 'health_disks', 'стан дисків': 'health_disks',
    # --- Команди з параметрами (базові тригери) ---
    'яка погода': 'weather', 'погода': 'weather', 'температура на вулиці': 'weather',
    'знайди в гуглі': 'google_search', 'пошук в інтернеті': 'google_search',
    'увімкни пісню': 'play_yt', 'постав музику': 'play_yt', 'включи музику': 'play_yt',
    'відкрий канал': 'yt_channel', 'покажи канал': 'yt_channel',
    'нагадай': 'reminder', 'нагадування': 'reminder',
    'скажи': 'qa_search', 'розкажи': 'qa_search', 'поясни': 'qa_search', 'відповідай': 'qa_search',
}

COMMAND_PATTERNS = [
    {'id': 'system_status', 'keywords': ['статус', 'система'], 'verbs': ['как'], 'patterns': ['как система', 'статус системы'], 'min_score': 75, 'description': 'Анализ текущей нагрузки на процессор, видеокарту и ОЗУ с выводом отчета', 'example': 'Джарвис, статус системы'},
    {'id': 'system_specs', 'keywords': ['характеристики', 'железо'], 'verbs': ['какое'], 'patterns': ['характеристики компьютера', 'какое железо'], 'min_score': 75, 'description': 'Технический обзор комплектующих: модель процессора, объем ОЗУ и видеокарта', 'example': 'Джарвис, характеристики компьютера'},
    {'id': 'shutdown_timer', 'keywords': ['выключи', 'через'], 'verbs': [], 'patterns': ['выключи через {N} минут', 'выключи пк через час'], 'min_score': 75, 'description': 'Планирование автоматического завершения работы через таймер обратного отсчета', 'example': 'Джарвис, выключи через полчаса'},
    {'id': 'cancel_timer', 'keywords': ['отмени', 'выключение'], 'verbs': [], 'patterns': ['отмени выключение', 'не выключай компьютер'], 'min_score': 75, 'description': 'Отмена активного запланированного выключения или перезагрузки', 'example': 'Джарвис, отмени выключение'},
    {'id': 'shutdown', 'keywords': ['компьютер'], 'verbs': ['выключи'], 'patterns': ['выключи компьютер', 'выключи пк'], 'min_score': 75, 'require_words': ['компьютер', 'пк'], 'description': 'Безопасное завершение работы Windows и выключение питания ПК', 'example': 'Джарвис, выключи компьютер'},
    {'id': 'restart', 'keywords': ['систему'], 'verbs': ['перезагрузи'], 'patterns': ['перезагрузи компьютер', 'перезагрузи систему'], 'min_score': 75, 'require_words': ['компьютер', 'систему', 'пк'], 'description': 'Принудительная перезагрузка ОС для исправления программных ошибок', 'example': 'Джарвис, перезагрузи систему'},
    {'id': 'system_cleanup', 'keywords': ['уборку', 'мусор'], 'verbs': ['сделай', 'очисти'], 'patterns': ['сделай уборку', 'очисти компьютер от мусора'], 'min_score': 75, 'description': 'Очистка системного кэша и временных файлов для освобождения места на диске', 'example': 'Джарвис, сделай уборку'},
    {'id': 'system_cleanup_deep', 'keywords': ['глубокую', 'старых', 'программ'], 'verbs': ['сделай', 'найди', 'проверь'], 'patterns': ['сделай глубокую уборку', 'найди мусор от старых программ'], 'min_score': 75, 'description': 'Поиск папок кэша от удалённых программ с подтверждением перед удалением', 'example': 'Джарвис, сделай глубокую уборку'},
    {'id': 'empty_trash', 'keywords': ['корзину'], 'verbs': ['очисти'], 'patterns': ['очисти корзину', 'выброси мусор из корзины'], 'min_score': 75, 'description': 'Безвозвратное удаление всех объектов из корзины Windows', 'example': 'Джарвис, очисти корзину'},
    {'id': 'economy_on', 'keywords': ['экономию'], 'verbs': ['включи'], 'patterns': ['включи режим экономии', 'экономь батарею'], 'min_score': 75, 'description': 'Снижение энергопотребления за счет яркости экрана и частоты процессора', 'example': 'Джарвис, включи экономию'},
    {'id': 'wifi_toggle', 'keywords': ['вай', 'фай', 'вайфай'], 'verbs': ['включи', 'выключи', 'отключи'], 'patterns': ['выключи вай фай', 'выключи вайфай', 'отключи интернет'], 'min_score': 75, 'description': 'Программное управление состоянием Wi-Fi адаптера', 'example': 'Джарвис, выключи вай фай'},
    {'id': 'bluetooth_toggle', 'keywords': ['блютуз'], 'verbs': ['включи', 'выключи', 'отключи'], 'patterns': ['выключи блютуз', 'включи блютуз'], 'min_score': 75, 'description': 'Управление модулем Bluetooth для подключения устройств', 'example': 'Джарвис, включи блютуз'},
    {'id': 'internet_speed', 'keywords': ['скорость', 'интернета'], 'verbs': ['проверь'], 'patterns': ['проверь скорость интернета', 'какой интернет'], 'min_score': 75, 'description': 'Замер пропускной способности сети и пинга до сервера', 'example': 'Джарвис, проверь интернет'},
    {'id': 'vol_up', 'keywords': ['громче', 'звук'], 'verbs': ['сделай'], 'patterns': ['сделай погромче', 'добавь звука'], 'min_score': 75, 'description': 'Увеличение уровня громкости системных динамиков на 10%', 'example': 'Джарвис, сделай погромче'},
    {'id': 'vol_down', 'keywords': ['тише', 'звук'], 'verbs': ['сделай'], 'patterns': ['сделай потише', 'убавь звук'], 'min_score': 75, 'description': 'Снижение уровня громкости системных динамиков на 10%', 'example': 'Джарвис, сделай потише'},
    {'id': 'vol_mute', 'keywords': ['звук'], 'verbs': ['выключи'], 'patterns': ['выключи звук', 'тишина'], 'min_score': 75, 'description': 'Мгновенное отключение звука на всех активных устройствах', 'example': 'Джарвис, выключи звук'},
    {'id': 'vol_set', 'keywords': ['громкость'], 'verbs': ['поставь'], 'patterns': ['громкость на 50', 'звук на 20'], 'min_score': 75, 'description': 'Установка точного уровня громкости в процентах', 'example': 'Джарвис, громкость на 40'},
    {'id': 'audio_switch', 'keywords': ['колонки', 'наушники'], 'verbs': ['переключи'], 'patterns': ['звук на наушники', 'звук на колонки'], 'min_score': 75, 'description': 'Перенаправление звукового потока между колонками и наушниками', 'example': 'Джарвис, звук на наушники'},
    {'id': 'brightness_set', 'keywords': ['яркость'], 'verbs': ['поставь'], 'patterns': ['яркость на 70', 'сделай экран ярче'], 'min_score': 75, 'description': 'Настройка уровня подсветки монитора в процентном соотношении', 'example': 'Джарвис, яркость на 80'},
    {'id': 'create_folder', 'keywords': ['папку'], 'verbs': ['создай'], 'patterns': ['создай папку', 'сделай новую папку'], 'min_score': 75, 'description': 'Создание новой папки в текущем пути с именованием голосом', 'example': 'Джарвис, создай папку Проекты'},
    {'id': 'delete_file', 'keywords': ['файл'], 'verbs': ['удали'], 'patterns': ['удали файл', 'сотри этот файл'], 'min_score': 75, 'description': 'Перемещение выбранного файла из текущей папки в корзину', 'example': 'Джарвис, удали файл заметка'},
    {'id': 'explorer_goto', 'keywords': ['папку'], 'verbs': ['открой', 'зайди'], 'patterns': ['открой папку', 'зайди в папку', 'открой в папку'], 'min_score': 70, 'description': 'Открытие произвольной папки по названию', 'example': 'Джарвис, открой папку Проекты'},
    {'id': 'explorer_go_up', 'keywords': ['папки', 'назад'], 'verbs': ['выйди', 'наверх'], 'patterns': ['выйди из папки', 'на уровень выше'], 'min_score': 75, 'description': 'Навигация в проводнике: возврат в родительскую директорию', 'example': 'Джарвис, выйди из папки'},
    {'id': 'create_word_doc', 'keywords': ['документ', 'ворд'], 'verbs': ['создай'], 'patterns': ['создай ворд', 'сделай новый документ'], 'min_score': 75, 'description': 'Создание и автоматическое открытие нового файла Word или Excel', 'example': 'Джарвис, создай документ ворд'},
    {'id': 'find_doc', 'keywords': ['документ'], 'verbs': ['найди', 'открой'], 'patterns': ['найди документ', 'открой файл', 'открой документ'], 'min_score': 75, 'description': 'Поиск файла по названию среди документов и его запуск', 'example': 'Джарвис, найди документ Отчет'},
    {'id': 'paste_file', 'keywords': ['файл'], 'verbs': ['вставь'], 'patterns': ['вставь файл', 'вставь последний файл'], 'min_score': 75, 'description': 'Вставка в текущую папку последнего скачанного или созданного файла', 'example': 'Джарвис, вставь файл'},
    {'id': 'min_win', 'keywords': ['окно'], 'verbs': ['сверни', 'минимизируй'], 'patterns': ['сверни окно', 'минимизируй окно', 'сверни это окно'], 'min_score': 80, 'description': 'Свернуть текущее активное окно', 'example': 'Джарвис, сверни окно'},
    {'id': 'min_all', 'keywords': ['окна', 'всё', 'все'], 'verbs': ['сверни'], 'patterns': ['сверни все окна', 'покажи рабочий стол'], 'min_score': 75, 'description': 'Свертывание всех открытых приложений на панель задач', 'example': 'Джарвис, сверни всё'},
    {'id': 'close_win', 'keywords': ['окно'], 'verbs': ['закрой'], 'patterns': ['закрой окно', 'закрой это'], 'min_score': 75, 'description': 'Завершение работы активного окна (эквивалент Alt+F4)', 'example': 'Джарвис, закрой это'},
    {'id': 'change_layout', 'keywords': ['раскладку', 'раскладка', 'язык', 'мову', 'розкладку', 'розкладка'], 'verbs': ['смени', 'переключи', 'поставь', 'включи', 'зміни', 'переключи'], 'patterns': ['смени раскладку', 'переключи язык', 'поставь английскую раскладку', 'включи русский язык', 'зміни розкладку', 'переключи мову'], 'min_score': 75, 'description': 'Переключение языка раскладки клавиатуры (русский/английский/украинский/немецкий)', 'example': 'Джарвис, переключи язык на английский'},
    {'id': 'win_snap_left', 'keywords': ['влево'], 'verbs': ['окно'], 'patterns': ['окно влево', 'прижми влево'], 'min_score': 75, 'description': 'Привязка активного окна к левой половине экрана', 'example': 'Джарвис, окно влево'},
    {'id': 'win_snap_right', 'keywords': ['вправо'], 'verbs': ['окно'], 'patterns': ['окно вправо', 'прижми вправо'], 'min_score': 75, 'description': 'Привязка активного окна к правой половине экрана', 'example': 'Джарвис, окно вправо'},
    {'id': 'ps_brush', 'keywords': ['кисть'], 'verbs': ['возьми'], 'patterns': ['возьми кисть', 'дай кисточку'], 'min_score': 75, 'description': 'Выбор основного инструмента рисования «Кисть» (B) в Photoshop', 'example': 'Джарвис, кисть'},
    {'id': 'ps_eraser', 'keywords': ['ластик'], 'verbs': ['возьми'], 'patterns': ['дай ластик', 'возьми стерку'], 'min_score': 75, 'description': 'Выбор инструмента «Ластик» (E) для стирания в Photoshop', 'example': 'Джарвис, ластик'},
    {'id': 'ps_save', 'keywords': ['проект'], 'verbs': ['сохрани'], 'patterns': ['сохрани проект', 'сохрани в фотошопе'], 'min_score': 75, 'description': 'Сохранение текущего состояния холста в файл .PSD (Ctrl+S)', 'example': 'Джарвис, сохрани проект'},
    {'id': 'figma_auto_layout', 'keywords': ['лейаут'], 'verbs': ['сделай'], 'patterns': ['сделай автолейаут', 'добавь лейаут'], 'min_score': 75, 'description': 'Применение функции Auto Layout к выделению в Figma (Shift+A)', 'example': 'Джарвис, автолейаут'},
    {'id': 'figma_group', 'keywords': ['сгруппируй'], 'verbs': [], 'patterns': ['сгруппируй', 'сделай группу'], 'min_score': 75, 'description': 'Объединение выделенных слоев в группу в Figma (Ctrl+G)', 'example': 'Джарвис, сгруппируй'},
    {'id': 'mouse_right', 'keywords': ['право'], 'verbs': ['веди'], 'patterns': ['мышка вправо', 'правее'], 'min_score': 75, 'description': 'Начало непрерывного движения курсора мыши вправо', 'example': 'Джарвис, мышка вправо'},
    {'id': 'media_pause', 'keywords': ['стоп', 'пауза'], 'verbs': ['останови', 'замри'], 'patterns': ['стоп', 'замри', 'хватит', 'поставь на паузу', 'останови видео'], 'min_score': 75, 'description': 'Мгновенная остановка движения курсора мыши или пауза медиа/видео', 'example': 'Джарвис, стоп'},
    {'id': 'media_play', 'keywords': ['продолжай', 'продолжить'], 'verbs': ['играй'], 'patterns': ['продолжай', 'продолжить видео', 'сними с паузы'], 'min_score': 75, 'description': 'Продолжение воспроизведения медиа/видео', 'example': 'Джарвис, продолжай'},
    {'id': 'mouse_faster', 'keywords': ['быстрее'], 'verbs': [], 'patterns': ['быстрее', 'ускорь мышку'], 'min_score': 75, 'description': 'Увеличение скорости движения курсора в 1.5 раза', 'example': 'Джарвис, быстрее'},
    {'id': 'weather', 'keywords': ['погода'], 'verbs': ['какая'], 'patterns': ['какая погода', 'температура на улице'], 'min_score': 75, 'description': 'Запрос текущего состояния погоды и прогноза температуры', 'example': 'Джарвис, какая погода?'},
    {'id': 'nasa_apod', 'keywords': ['наса', 'nasa'], 'verbs': ['покажи', 'дай', 'найди'], 'require_words': ['наса', 'nasa'], 'patterns': ['картинка дня от наса', 'снимок дня наса', 'астрономическая картинка дня от наса', 'что нового в космосе от наса', 'покажи картинку дня от nasa'], 'min_score': 75, 'description': 'Астрономическая картинка дня NASA (APOD) с описанием', 'example': 'Джарвис, покажи картинку дня от наса'},
    {'id': 'song_id', 'keywords': ['песня', 'пісня', 'трек', 'играет', 'грає'], 'verbs': ['угадай', 'узнай', 'распознай', 'вгадай', 'впізнай', 'розпізнай'], 'require_words': ['песн', 'пісн', 'трек', 'играет', 'грає'], 'patterns': ['что за песня играет', 'что это за песня', 'угадай песню', 'узнай песню', 'какая это песня', 'что за трек', 'что играет сейчас', 'що за пісня грає', 'вгадай пісню', 'яка це пісня'], 'min_score': 75, 'description': 'Определяет, какая песня сейчас играет (по звуку с микрофона или с компьютера)', 'example': 'Джарвис, что за песня играет?'},
    {'id': 'reminder', 'keywords': ['напомни'], 'verbs': [], 'extras': ['напомни через', 'напомни мне', 'поставь напоминание', 'сделай напоминание', 'нагадай мені', 'через'], 'patterns': ['напомни через {N} минут', 'напомни через {N} часа', 'напомни через час', 'сделай напоминание', 'напомни мне через {N} минут'], 'min_score': 75, 'description': 'Установка голосового напоминания с обратным отсчетом', 'example': 'Джарвис, напомни выпить таблетки через 10 минут'},
    {'id': 'timer_set', 'keywords': ['таймер'], 'verbs': ['поставь', 'засеки', 'запусти'], 'patterns': ['поставь таймер на {N} минут', 'засеки {N} минут', 'таймер на час', 'таймер на {N} минут'], 'min_score': 75, 'description': 'Запуск таймера обратного отсчёта с предупреждениями', 'example': 'Джарвис, поставь таймер на тридцать минут'},
    {'id': 'timer_add', 'keywords': ['таймер', 'добавь', 'продли'], 'verbs': ['добавь', 'продли'], 'patterns': ['добавь {N} минут к таймеру', 'продли таймер на {N} минут'], 'min_score': 75, 'description': 'Добавить время к активному таймеру', 'example': 'Джарвис, добавь 15 минут'},
    {'id': 'timer_status', 'keywords': ['таймер', 'осталось'], 'verbs': ['сколько'], 'patterns': ['сколько осталось на таймере', 'сколько времени осталось'], 'min_score': 75, 'description': 'Узнать сколько осталось на таймере', 'example': 'Джарвис, сколько осталось'},
    {'id': 'timer_cancel', 'keywords': ['таймер'], 'verbs': ['отмени', 'сбрось'], 'patterns': ['отмени таймер', 'сбрось таймер'], 'min_score': 75, 'description': 'Отменить активный таймер', 'example': 'Джарвис, отмени таймер'},
    {'id': 'google_search', 'keywords': ['гугле'], 'verbs': ['найди'], 'patterns': ['найди в гугле', 'поиск в интернете'], 'min_score': 75, 'description': 'Автоматический поиск заданного запроса в поисковой системе Google', 'example': 'Джарвис, найди в гугле рецепт'},
    {'id': 'git_commit', 'keywords': ['коммит'], 'verbs': ['сделай'], 'patterns': ['сделай коммит', 'отправь изменения'], 'min_score': 75, 'description': 'Автоматизация Git: добавление всех файлов, коммит и пуш в облако', 'example': 'Джарвис, сделай коммит'},
    {'id': 'open_browser', 'keywords': ['браузер'], 'verbs': ['открой', 'запусти'], 'patterns': ['открой браузер', 'запусти браузер'], 'min_score': 75, 'description': 'Открытие веб-браузера', 'example': 'Джарвис, открой браузер'},
    {'id': 'open_discord', 'keywords': ['дискорд', 'discord'], 'verbs': ['открой', 'запусти'], 'patterns': ['открой дискорд', 'запусти дискорд'], 'min_score': 75, 'description': 'Открытие Discord', 'example': 'Джарвис, открой дискорд'},
    {'id': 'open_telegram', 'keywords': ['телеграм', 'телегу', 'telegram'], 'verbs': ['открой', 'запусти'], 'patterns': ['открой телеграм', 'запусти телегу'], 'min_score': 75, 'description': 'Открытие Telegram', 'example': 'Джарвис, открой телеграм'},
    {'id': 'open_photoshop', 'keywords': ['фотошоп', 'photoshop'], 'verbs': ['открой', 'запусти'], 'patterns': ['открой фотошоп', 'запусти фотошоп'], 'min_score': 75, 'description': 'Открытие Adobe Photoshop', 'example': 'Джарвис, открой фотошоп'},
    {'id': 'open_steam', 'keywords': ['стим', 'steam'], 'verbs': ['открой', 'запусти'], 'patterns': ['открой стим', 'запусти стим'], 'min_score': 75, 'description': 'Открытие Steam', 'example': 'Джарвис, открой стим'},
    {'id': 'play_yt', 'keywords': ['песню', 'видео', 'музыку', 'песня', 'трек', 'клип', 'ютубе', 'ютуб', 'youtube'], 'verbs': ['включи', 'поставь', 'найди'], 'patterns': ['включи песню', 'поставь видео', 'найди музыку', 'включи клип', 'включи на ютубе'], 'min_score': 70, 'description': 'Поиск и воспроизведение видео или музыки на YouTube', 'example': 'Джарвис, включи песню Linkin Park'},
    {'id': 'yt_channel', 'keywords': ['канал', 'канала'], 'verbs': ['открой', 'покажи', 'найди'], 'patterns': ['открой канал', 'покажи канал на ютубе', 'запусти канал'], 'min_score': 75, 'description': 'Открытие указанного YouTube канала', 'example': 'Джарвис, открой канал Wylsacom'},
    {'id': 'qa_search', 'keywords': ['скажи', 'ответь', 'расскажи', 'объясни'], 'verbs': ['скажи', 'ответь', 'расскажи', 'объясни'], 'patterns': ['скажи {N}', 'ответь {N}', 'расскажи {N}', 'объясни {N}'], 'min_score': 65, 'description': 'Запрос к искусственному интеллекту для получения ответа на любой вопрос', 'example': 'Джарвис, скажи кто такой Никола Тесла'},
    {'id': 'set_weather_city', 'keywords': ['город'], 'verbs': ['установи', 'запомни', 'смени'], 'patterns': ['установи город Москва', 'мой город Санкт-Петербург', 'смени город на Лондон'], 'min_score': 75, 'description': 'Установка города для прогноза погоды вручную', 'example': 'Джарвис, установи город Москва'},
    {'id': 'reactor_color_red', 'keywords': ['красный'], 'verbs': ['сделай', 'покрась', 'смени'], 'require_words': ['реактор', 'реактора'], 'patterns': ['сделай реактор красным', 'покрась реактор в красный', 'смени цвет реактора на красный'], 'min_score': 75, 'description': 'Смена цвета реактора HUD на красный', 'example': 'Джарвис, сделай реактор красным'},
    {'id': 'reactor_color_cyan', 'keywords': ['синий', 'голубой'], 'verbs': ['сделай', 'покрась', 'смени'], 'require_words': ['реактор', 'реактора'], 'patterns': ['сделай реактор синим', 'покрась реактор в голубой', 'смени цвет реактора на синий'], 'min_score': 75, 'description': 'Смена цвета реактора HUD на синий', 'example': 'Джарвис, сделай реактор синим'},
    {'id': 'reactor_color_green', 'keywords': ['зелёный', 'зеленый'], 'verbs': ['сделай', 'покрась', 'смени'], 'require_words': ['реактор', 'реактора'], 'patterns': ['сделай реактор зелёным', 'покрась реактор в зеленый', 'смени цвет реактора на зелёный'], 'min_score': 75, 'description': 'Смена цвета реактора HUD на зелёный', 'example': 'Джарвис, сделай реактор зелёным'},
    {'id': 'reactor_color_amber', 'keywords': ['жёлтый', 'желтый', 'оранжевый'], 'verbs': ['сделай', 'покрась', 'смени'], 'require_words': ['реактор', 'реактора'], 'patterns': ['сделай реактор жёлтым', 'покрась реактор в оранжевый', 'смени цвет реактора на жёлтый'], 'min_score': 75, 'description': 'Смена цвета реактора HUD на жёлтый/оранжевый', 'example': 'Джарвис, сделай реактор жёлтым'},
    {'id': 'reactor_color_magenta', 'keywords': ['фиолетовый', 'пурпурный'], 'verbs': ['сделай', 'покрась', 'смени'], 'require_words': ['реактор', 'реактора'], 'patterns': ['сделай реактор фиолетовым', 'покрась реактор в пурпурный', 'смени цвет реактора на фиолетовый'], 'min_score': 75, 'description': 'Смена цвета реактора HUD на фиолетовый', 'example': 'Джарвис, сделай реактор фиолетовым'},
    {'id': 'reactor_color_white', 'keywords': ['белый'], 'verbs': ['сделай', 'покрась', 'смени'], 'require_words': ['реактор', 'реактора'], 'patterns': ['сделай реактор белым', 'покрась реактор в белый', 'смени цвет реактора на белый'], 'min_score': 75, 'description': 'Смена цвета реактора HUD на белый', 'example': 'Джарвис, сделай реактор белым'},
    {'id': 'reactor_reset', 'keywords': ['обычный'], 'verbs': ['верни', 'сбрось'], 'require_words': ['реактор', 'реактора'], 'patterns': ['верни реактор', 'сбрось цвет реактора', 'обычный цвет реактора'], 'min_score': 75, 'description': 'Сброс цвета реактора HUD к обычному режимному цвету', 'example': 'Джарвис, верни реактор'},
    {'id': 'reactor_pulse', 'keywords': ['пульс'], 'verbs': ['запусти', 'сделай'], 'require_words': ['реактор', 'реактора'], 'patterns': ['пульс реактора', 'запусти пульсацию реактора', 'сделай пульс на реакторе'], 'min_score': 75, 'description': 'Разовый эффект усиленной пульсации реактора HUD', 'example': 'Джарвис, пульс реактора'},
    {'id': 'reactor_glitch', 'keywords': ['глитч'], 'verbs': ['тряхни', 'запусти'], 'require_words': ['реактор', 'реактора', 'реакторе'], 'patterns': ['тряхни реактор', 'глитч реактора', 'запусти глитч на реакторе'], 'min_score': 75, 'description': 'Разовый эффект глитч-тряски реактора HUD', 'example': 'Джарвис, тряхни реактор'},
]
