"""Photoshop/Figma app-context shortcut phrase tables (_PS_SHORT / _FIGMA_SHORT).
Split out of commands_data.py purely for file size (that file crossed 600
lines after the 2026-09 pass that filled in voice phrases for previously
orphaned ps_*/figma_* hotkey actions — see tests/test_creative_commands.py).
No behavior change; commands_data.py re-imports both dicts so existing
imports keep working.
"""

_PS_SHORT = {
    'покажи слои': 'ps_layers_panel',
    'покажи слой': 'ps_layers_panel',
    'слои': 'ps_layers_panel',
    'слой': 'ps_layers_panel',
    'покажи кисти': 'ps_brushes_panel',
    'покажи цвета': 'ps_color_panel',
    'покажи панель слоев': 'ps_layers_panel',
    'покажи панель кистей': 'ps_brushes_panel',
    'покажи панель цветов': 'ps_color_panel',
    'кисть': 'ps_brush',
    'возьми кисть': 'ps_brush',
    'выбери кисть': 'ps_brush',
    'инструмент кисть': 'ps_brush',
    'ластик': 'ps_eraser',
    'выбери ластик': 'ps_eraser',
    'инструмент ластик': 'ps_eraser',
    'перемещение': 'ps_move',
    'инструмент перемещение': 'ps_move',
    'текст': 'ps_text',
    'инструмент текст': 'ps_text',
    'пипетка': 'ps_eyedropper',
    'инструмент пипетка': 'ps_eyedropper',
    'прямоугольник': 'ps_marquee',
    'выделение прямоугольником': 'ps_marquee',
    'выделение': 'ps_lasso',
    'лассо': 'ps_lasso',
    'рука': 'ps_hand',
    'масштаб': 'ps_zoom',
    'зум': 'ps_zoom',
    'увеличить': 'ps_zoom_in',
    'уменьшить': 'ps_zoom_out',
    'по размеру': 'ps_fit',
    'сто процентов': 'ps_100',
    'отмена': 'ps_undo',
    'повтори': 'ps_redo',
    'сохранить': 'ps_save',
    'сохранить как': 'ps_save_as',
    'новый слой': 'ps_new_layer',
    'дубликат слоя': 'ps_dup_layer',
    'трансформация': 'ps_transform',
    'заливка': 'ps_fill',
    'снять выделение': 'ps_deselect',
    'выделить все': 'ps_select_all',
    'экспортировать': 'ps_export_as',
    'экспортировать как': 'ps_export_as',
    'экспорт': 'ps_export_as',
    'объединить слои': 'ps_merge_down',
    'объедини слои': 'ps_merge_down',
    'сгруппировать': 'ps_group',
    'сгруппируй': 'ps_group',
    'разгруппировать': 'ps_ungroup',
    'разгруппируй': 'ps_ungroup',
    'инвертировать': 'ps_invert',
    'инверсия': 'ps_invert',
    'уровни': 'ps_levels',
    'кривые': 'ps_curves',
    'цветовой тон': 'ps_hue_sat',
    'тон и насыщенность': 'ps_hue_sat',
    'цветовой баланс': 'ps_color_balance',
    'маска': 'ps_mask',
    'добавить маску': 'ps_mask',
    'цвета по умолчанию': 'ps_default_colors',
    'поменять цвета': 'ps_swap_colors',
}
_PS_SHORT.update({
    'создай слой': 'ps_new_layer',
    'создать слой': 'ps_new_layer',
    'создай новый слой': 'ps_new_layer',
    'создать новый слой': 'ps_new_layer',
    'пипетку': 'ps_eyedropper',
    'возьми пипетку': 'ps_eyedropper',
    'выбери пипетку': 'ps_eyedropper',
    'инструмент пипетка': 'ps_eyedropper',
    'возьми инструмент пипетка': 'ps_eyedropper',
    'выбери инструмент пипетка': 'ps_eyedropper',
})
_FIGMA_SHORT = {
    'фрейм': 'figma_frame',
    'рамка': 'figma_frame',
    'прямоугольник': 'figma_rect',
    'круг': 'figma_ellipse',
    'линия': 'figma_line',
    'стрелка': 'figma_arrow',
    'перо': 'figma_pen',
    'текст': 'figma_text',
    'рука': 'figma_hand',
    'масштаб': 'figma_zoom',
    'зум': 'figma_zoom',
    'увеличить': 'figma_zoom_in',
    'уменьшить': 'figma_zoom_out',
    'по размеру': 'figma_fit',
    'отмена': 'figma_undo',
    'повтори': 'figma_redo',
    'сохранить': 'figma_save',
    'дубликат': 'figma_duplicate',
    'группа': 'figma_group',
    'сгруппировать': 'figma_group',
    'разгруппировать': 'figma_ungroup',
    'автолейаут': 'figma_auto_layout',
    'компонент': 'figma_component',
    'экспорт': 'figma_export',
    'копировать': 'figma_copy',
    'вставить': 'figma_paste',
    'показать интерфейс': 'figma_toggle_ui',
    'показать ui': 'figma_toggle_ui',
    'выровнять по левому краю': 'figma_align_left',
    'по левому краю': 'figma_align_left',
    'выровнять по центру': 'figma_align_center',
    'по центру': 'figma_align_center',
    'выровнять по правому краю': 'figma_align_right',
    'по правому краю': 'figma_align_right',
    'выровнять по верхнему краю': 'figma_align_top',
    'по верхнему краю': 'figma_align_top',
    'выровнять по середине': 'figma_align_middle',
    'по середине': 'figma_align_middle',
    'выровнять по нижнему краю': 'figma_align_bottom',
    'по нижнему краю': 'figma_align_bottom',
    'на передний план': 'figma_bring_front',
    'вынести вперед': 'figma_bring_front',
    'на задний план': 'figma_send_back',
    'отправить назад': 'figma_send_back',
    'переместить вперед': 'figma_bring_forward',
    'на уровень вперед': 'figma_bring_forward',
    'переместить назад': 'figma_send_backward',
    'на уровень назад': 'figma_send_backward',
    'отсоединить инстанс': 'figma_detach_instance',
    'отсоединить компонент': 'figma_detach_instance',
    'снять выделение': 'figma_deselect',
    'выделить все': 'figma_select_all',
    'заблокировать': 'figma_lock',
    'заблокируй': 'figma_lock',
    'скрыть': 'figma_hide',
    'спрятать': 'figma_hide',
}
