<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>PlanetbaseTelemetry</AssemblyName>
    <RootNamespace>PlanetbaseTelemetry</RootNamespace>
    <OutputPath>bin\Release</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Configuration>Release</Configuration>
    <Optimize>true</Optimize>
    <Nullable>disable</Nullable>
    <PB>C:\Program Files (x86)\Steam\steamapps\common\Planetbase\Planetbase_Data\Managed</PB>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(PB)\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(PB)\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
